# Generated by Django 4.0.4 on 2022-05-29 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_musclegroup_workout_exercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='muscleGroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise_group', to='api.musclegroup'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='muscleGroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workout_group', to='api.musclegroup'),
        ),
    ]
