# Generated by Django 4.0.4 on 2022-05-29 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_bmi'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmi',
            name='bmi',
            field=models.CharField(default='', max_length=300),
        ),
    ]
