# Generated by Django 4.0.4 on 2022-05-29 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_bmi_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='musclegroup',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='workout',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
